import type { Product } from '@/lib/types/store';

// Seed catalog shown until a live Firebase `products` collection is connected.
export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'tpx-rehearsal-tee',
    name: 'TPX Rehearsal Tee',
    slug: 'tpx-rehearsal-tee',
    description: 'Heavyweight cotton tee from the rehearsal room. Relaxed fit, tonal logo.',
    price: 3500,
    currency: 'usd',
    type: 'physical',
    status: 'active',
    images: [],
    inventory: 42,
    tags: ['apparel', 'new'],
    category: 'apparel',
    featured: true,
  },
  {
    id: 'legacy-hoodie',
    name: 'Legacy Hoodie',
    slug: 'legacy-hoodie',
    description: 'Brushed-fleece hoodie with embroidered wordmark. Limited run.',
    price: 6500,
    compareAtPrice: 8000,
    currency: 'usd',
    type: 'physical',
    status: 'active',
    images: [],
    inventory: 25,
    tags: ['apparel', 'limited'],
    category: 'apparel',
    featured: true,
  },
  {
    id: 'tpx-cap',
    name: 'TPX Cap',
    slug: 'tpx-cap',
    description: 'Structured six-panel cap with gold embroidery.',
    price: 3000,
    currency: 'usd',
    type: 'physical',
    status: 'active',
    images: [],
    inventory: 60,
    tags: ['accessories'],
    category: 'accessories',
  },
  {
    id: 'signed-tour-poster',
    name: 'Signed Tour Poster',
    slug: 'signed-tour-poster',
    description: 'Archival print, hand-signed by Travis Payne. Numbered edition of 100.',
    price: 12000,
    currency: 'usd',
    type: 'physical',
    status: 'active',
    images: [],
    inventory: 100,
    tags: ['signed', 'limited'],
    category: 'signed',
    featured: true,
  },
  {
    id: 'movement-is-the-message-ebook',
    name: 'Movement Is the Message (eBook)',
    slug: 'movement-is-the-message-ebook',
    description: 'A digital field guide to choreographic process. Instant download.',
    price: 1500,
    currency: 'usd',
    type: 'digital',
    status: 'active',
    images: [],
    inventory: -1,
    tags: ['digital'],
    category: 'digital',
  },
  {
    id: 'tpx-tote',
    name: 'TPX Studio Tote',
    slug: 'tpx-studio-tote',
    description: 'Heavy canvas tote for the studio and beyond.',
    price: 2500,
    currency: 'usd',
    type: 'physical',
    status: 'active',
    images: [],
    inventory: 80,
    tags: ['accessories'],
    category: 'accessories',
  },
];
